- name: Update apt-get
  apt:
    update_cache: yes

- name: Set microservice directory path
  set_fact:
    project_dir: /var/project/microservice-app

- name: Add node
  shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

- name: Installing nodejs, nginx, build-essential
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - nginx
    - build-essential

- name: create project directory
  file:
    path: /var/project
    state: directory

- name: clone the microservice repo
  git:
    repo: https://github.com/rinormaloku/k8s-mastery.git
    dest: /var/project/microservice-app
